
import type { AppProps } from "next/app";
import 'bulma/css/bulma.css'
import '@/Styles/global.css'
import Head from "next/head";


export default function App({ Component, pageProps }: AppProps) {
  return (

<>
          <Head>
        <title>Manutenção Elétrica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/main.png" />
      </Head>
        <Component {...pageProps} />
</>

  );
}
